### PR TITLE
nymph2_2/reorganize-directories2

### PR DESCRIPTION
**Pull request by zieglerad**
Draft PR for automatic builds.

### CODE REVIEW

**Review by nsoblath — CHANGES_REQUESTED** [review]
I like the approach you've taken here, but I have two major comments that need to be addressed:
1. With one unfortunate exception, the standard for directory and file names is to use camel case.  So the `cpp` and `python` directories need to be renamed `Cpp` and `Python`, respectively.  Hopefully with some clever text replace this'll be relatively painless.  If you use a Mac, you may already know to do this, but I highly recommend using a Linux machine (or container, etc) to change the case of the directories because the Mac filesystem is not case sensitive.
2. It looks like the files from the old library (in the `Library_v1` directory) have gotten mixed in with the updated files from the `Library` directory.  Those need to be pulled back out.  Also, none of the executables have been updated yet and the things in `Executables/Validation` aren't going to be used (in favor of brand new tests using Catch2).  So let's rename `Executables` to `Executables_v1` to avoid future mixups.

**Comment by MCFlowMace** [comment]
Responding to 1. from Noah: 
Where does the camel case rule come from? Generally I think it is okay, but when we want to stick to PEP8 for the python side it cannot be applied to the subdirectories of the `Python` directory. Those would define the python packages, which need 'short, all-lowercase names' https://www.python.org/dev/peps/pep-0008/#package-and-module-names .

**Comment by nsoblath** [comment]
@MCFlowMace Within the Python side of the project the PEP8 standard should certainly be followed.  Camel case is used on the C++ side by both Nymph and Katydid, and so I think it'll be easier to stick with that.  As far as what to do for the top-level directories in the Nymph repo, I'd suggest sticking with camel case since that's what most of the other top-level directories use.

**Review by MCFlowMace — APPROVED** [review]
Overall looks good to me. `cpp` and `python` directories still have to be renamed themselves. For this reason it does not build at the moment because it has already changed in the makefiles. I approve the PR since I assume you will not merge before it builds correctly.

**Review by zieglerad — COMMENTED** [review]
Thanks, for the feedback. I think I've resorted everything how it should be now.

**Comment by MCFlowMace** [comment]
@zieglerad I think you copied `cpp` and `python` instead of renaming them. I have two versions of both directories now.

**Comment by zieglerad** [comment]
@MCFlowMace Thanks, fixed now I think.

**Review by nsoblath — APPROVED** [review]
Approved pending automatic tests

**Pull request merged**
